# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb84e7d4bb377e66228f85112e05401c94926913b916f76f245ba381c97fc173a92dcc53557878896f06017a867b405849aabc4ac62e7e0c1e25858166ef808b

test:
  secret_key_base: 4eff5913b7f60d7b5336316314be4dbd78f332cb78c76660150f63e1d5117b6cede1ec55ba3d87a5a30ea03db1eb3be78a9966da2dc3500c5b4faf8e01e2a637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
